/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC20SymbolBytes,
  ERC20SymbolBytesInterface,
} from "../ERC20SymbolBytes";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC20SymbolBytes__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20SymbolBytesInterface {
    return new Interface(_abi) as ERC20SymbolBytesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC20SymbolBytes {
    return new Contract(address, _abi, runner) as unknown as ERC20SymbolBytes;
  }
}
