/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { TOB, TOBInterface } from "../TOB";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tOLP",
        type: "address",
      },
      {
        internalType: "address",
        name: "_oTAP",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "_tapOFT",
        type: "address",
      },
      {
        internalType: "address",
        name: "_paymentTokenBeneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_epochDuration",
        type: "uint256",
      },
      {
        internalType: "contract IPearlmit",
        name: "_pearlmit",
        type: "address",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "AdvanceEpochFirst",
    type: "error",
  },
  {
    inputs: [],
    name: "DurationTooShort",
    type: "error",
  },
  {
    inputs: [],
    name: "Failed",
    type: "error",
  },
  {
    inputs: [],
    name: "LockExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "LockNotExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "NoActiveSingularities",
    type: "error",
  },
  {
    inputs: [],
    name: "NoLiquidity",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAuthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEqualDurations",
    type: "error",
  },
  {
    inputs: [],
    name: "OneEpochCooldown",
    type: "error",
  },
  {
    inputs: [],
    name: "OptionExpired",
    type: "error",
  },
  {
    inputs: [],
    name: "PaymentTokenNotSupported",
    type: "error",
  },
  {
    inputs: [],
    name: "PaymentTokenValuationNotValid",
    type: "error",
  },
  {
    inputs: [],
    name: "PositionNotValid",
    type: "error",
  },
  {
    inputs: [],
    name: "SingularityInRescueMode",
    type: "error",
  },
  {
    inputs: [],
    name: "TooHigh",
    type: "error",
  },
  {
    inputs: [],
    name: "TooLong",
    type: "error",
  },
  {
    inputs: [],
    name: "TooLow",
    type: "error",
  },
  {
    inputs: [],
    name: "TooSoon",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "cumulative",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "averageMagnitude",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalParticipants",
        type: "uint256",
      },
    ],
    name: "AMLDivergence",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract ERC20",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "otapTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tapAmount",
        type: "uint256",
      },
    ],
    name: "ExerciseOption",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "otapTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tolpTokenId",
        type: "uint256",
      },
    ],
    name: "ExitPosition",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "extractedTap",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "epochTapValuation",
        type: "uint256",
      },
    ],
    name: "NewEpoch",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "sglAssetId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalDeposited",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "otapTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tolpTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "discount",
        type: "uint256",
      },
    ],
    name: "Participate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IPearlmit",
        name: "oldPearlmit",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract IPearlmit",
        name: "newPearlmit",
        type: "address",
      },
    ],
    name: "PearlmitUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract ERC20",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract ITapiocaOracle",
        name: "oracle",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "oracleData",
        type: "bytes",
      },
    ],
    name: "SetPaymentToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract ITapiocaOracle",
        name: "oracle",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "oracleData",
        type: "bytes",
      },
    ],
    name: "SetTapOracle",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "EPOCH_DURATION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_WEIGHT_FACTOR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_paymentTokens",
        type: "address[]",
      },
    ],
    name: "collectPaymentTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "emissionsStartTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epochTAPValuation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_oTAPTokenID",
        type: "uint256",
      },
      {
        internalType: "contract ERC20",
        name: "_paymentToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tapAmount",
        type: "uint256",
      },
    ],
    name: "exerciseOption",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_oTAPTokenID",
        type: "uint256",
      },
    ],
    name: "exitPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentWeek",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_oTAPTokenID",
        type: "uint256",
      },
      {
        internalType: "contract ERC20",
        name: "_paymentToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tapAmount",
        type: "uint256",
      },
    ],
    name: "getOTCDealDetails",
    outputs: [
      {
        internalType: "uint256",
        name: "eligibleTapAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "paymentTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tapAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sglAssetID",
        type: "uint256",
      },
    ],
    name: "netDepositedForEpoch",
    outputs: [
      {
        internalType: "int256",
        name: "netAmount",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "newEpoch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "oTAP",
    outputs: [
      {
        internalType: "contract OTAP",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "oTAPCalls",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "participants",
    outputs: [
      {
        internalType: "bool",
        name: "hasVotingPower",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "divergenceForce",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "averageMagnitude",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tOLPTokenID",
        type: "uint256",
      },
    ],
    name: "participate",
    outputs: [
      {
        internalType: "uint256",
        name: "oTAPTokenID",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paymentTokenBeneficiary",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ERC20",
        name: "",
        type: "address",
      },
    ],
    name: "paymentTokens",
    outputs: [
      {
        internalType: "contract ITapiocaOracle",
        name: "oracle",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "oracleData",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pearlmit",
    outputs: [
      {
        internalType: "contract IPearlmit",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_minWeightFactor",
        type: "uint256",
      },
    ],
    name: "setMinWeightFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_pauseState",
        type: "bool",
      },
    ],
    name: "setPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ERC20",
        name: "_paymentToken",
        type: "address",
      },
      {
        internalType: "contract ITapiocaOracle",
        name: "_oracle",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_oracleData",
        type: "bytes",
      },
    ],
    name: "setPaymentToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_paymentTokenBeneficiary",
        type: "address",
      },
    ],
    name: "setPaymentTokenBeneficiary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPearlmit",
        name: "_pearlmit",
        type: "address",
      },
    ],
    name: "setPearlmit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ITapiocaOracle",
        name: "_tapOracle",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_tapOracleData",
        type: "bytes",
      },
    ],
    name: "setTapOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_virtualTotalAmount",
        type: "uint256",
      },
    ],
    name: "setVirtualTotalAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "singularityGauges",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tOLP",
    outputs: [
      {
        internalType: "contract TapiocaOptionLiquidityProvision",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tapOFT",
    outputs: [
      {
        internalType: "contract TapToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tapOracle",
    outputs: [
      {
        internalType: "contract ITapiocaOracle",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tapOracleData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "timestampToWeek",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "twAML",
    outputs: [
      {
        internalType: "uint256",
        name: "totalParticipants",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "averageMagnitude",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDeposited",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cumulative",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TOB__factory {
  static readonly abi = _abi;
  static createInterface(): TOBInterface {
    return new Interface(_abi) as TOBInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TOB {
    return new Contract(address, _abi, runner) as unknown as TOB;
  }
}
